### ISSUE TITLE
Feature - Add ability to disable resize operation.

### ISSUE THREAD

**Issue by th3raid0r** [Djdefrag/RealScaler#1]
I'm often working with 480p DVD images and find that resizing doesn't benefit me in any way. Yet the resize operation takes a very long time.

As a user, I'd like the ability to turn that "feature" off. If this option already exists, I cannot locate it.

**Comment by th3raid0r** [comment]
In the meantime, I'm going to see if I can somehow decompile the exe and just comment out - https://github.com/Djdefrag/ReSR.Scaler/blob/0fe61ba9239a82f25eef7648dfebf590b9c5ae5f/ReSR.Scaler.py#L1374

**Comment by Djdefrag** [comment]
Hi, yes, of course there will be improvements in this direction. :)
