### ISSUE TITLE
Upscale Failed

### ISSUE THREAD

**Issue by berdancanyet** [Djdefrag/RealScaler#10]
![image](https://github.com/Djdefrag/RealScaler/assets/13546853/86bfff40-302b-4422-aece-b5076606e4c1)

**Comment by Djdefrag** [comment]
Hi my friend,

are you using github code? Maibe you do not have AI .pth files, you can download them here: https://github.com/xinntao/Real-ESRGAN

**Comment by berdancanyet** [comment]
Thanks man!
Real-ESRGAN model zoo doesn't contain the ones i need.
![image](https://github.com/Djdefrag/RealScaler/assets/13546853/ea3841cd-7c42-4d8f-b9b1-6504a8696426)

What is your telegram address?

**Comment by Djdefrag** [comment]
Yeah... i changed filenames bacause they were confusing.

You can contact me here: https://linktr.ee/j3ngystudio
