### ISSUE TITLE
error while switching to high performace gpu option

### ISSUE THREAD

**Issue by replicate632** [Djdefrag/RealScaler#15]
![Screenshot 2024-03-31 183210](https://github.com/Djdefrag/RealScaler/assets/157591827/00bc0e44-bb32-4097-a948-b79fef61c9bc)

**Comment by Djdefrag** [comment]
Hi mi friend, 

do you have multiple gpus?

**Comment by replicate632** [comment]
yes one is integrated intel and other is nvidia, i tried selecting the app to run by nvidia in both nvidia control pannel and in windows settings ( high performance)

**Comment by Djdefrag** [comment]
Hi my friend, this is strange, can you screenshot your TaskManager on Performance tab?

there are all informations about your pc

**Comment by Djdefrag** [comment]
Mmmh, hi my friend

sadly the Nvidia GT 650m seems not compatible with DirectML :(

**Comment by replicate632** [comment]
![Uploading Screenshot_20240410_072838.jpg…]()

**Comment by replicate632** [comment]
Al good
