### ISSUE TITLE
Unable to select proper GPU

### ISSUE THREAD

**Issue by franzkruhm** [Djdefrag/RealScaler#16]
Hello,
I have 3 GPUs on my laptop
Integrated
built-in 2060
and 3060 in eGPU enclose.

I can only select integrated, I'd like to be able to switch to 3060, I dig some digging in the code I can only find 
providers = [('DmlExecutionProvider', {'device_id': '0'})] for "high performance" but that just uses the Intel integrated.
Any idea?

**Comment by Djdefrag** [comment]
Hi my friend,

yes, id:0 usually is the high performance gpu.

Have you tried select Power saving GPU? it should select one of your 2 Nvidia gpus

I do not recommend external gpu as it has very limited bandwidth capacity, this could slow down the AI process a lot

**Comment by franzkruhm** [comment]
hello, thanks for getting back to me

so id:0 does indeed use the 3060, it just didn't show cuda usage, I only realized it when checking GPU temperature

power saving goes to intel graphics.

thanks, again, it works as expected after all
