### ISSUE TITLE
Could not find tag for codec pcm_s16le in stream #1, codec not currently supported in container\r\nCould not write header for output file #0 (incorrect codec parameters ?): Invalid argument\r\nError initializing output stream 0:0 -- \r\n'

### ISSUE THREAD

**Issue by PrittSpadeLord** [Djdefrag/RealScaler#22]
I encounter this error after the video upscaling is complete and is processing:

Error [Errno 22] Invalid argument

MoviePy error: FFMPEG encountered the following error while writing file C:/Users/Hi/Videos/Genshin Impact/Ning3/Ningguang_vert_RealSRx4_Anime_Resize-25_Interpolation-High.mp4:

 b'[mp4 @ 000001c54a97dac0] Could not find tag for codec pcm_s16le in stream #1, codec not currently supported in container\r\nCould not write header for output file #0 (incorrect codec parameters ?): Invalid argument\r\nError initializing output stream 0:0 -- \r\n'

The video export failed, possibly because the codec specified for the video (libx264) is not compatible with the given extension (mp4). Please specify a valid 'codec' argument in write_videofile. This would be 'libx264' or 'mpeg4' for mp4, 'libtheora' for ogv, 'libvpx for webm. Another possible reason is that the audio codec was not compatible with the video codec. For instance the video extensions 'ogv' and 'webm' only allow 'libvorbis' (default) as avideo codec.

**Comment by Djdefrag** [comment]
Hi my friend, 

you need the newer version of ffmpeg.exe

1. Download ffmpeg-release-essentials.7z from here https://www.gyan.dev/ffmpeg/builds/
2. Extract ffmpeg.exe and place it in /Assets folder
3. Open the app, and it will automatically find the new ffmpeg version
